# Generated by Django 2.1.7 on 2019-05-01 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('P8', '0002_categories_produit_profil_substitut'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitut',
            name='USER_FAVORITE',
            field=models.OneToOneField(default=1, on_delete=ChildProcessError, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
