# Generated by Django 2.1.7 on 2019-05-02 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P8', '0006_profil_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitut',
            name='USER_FAVORITE',
            field=models.ForeignKey(on_delete=ChildProcessError, to=settings.AUTH_USER_MODEL),
        ),
    ]
