# Generated by Django 2.1.7 on 2019-05-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P8', '0004_auto_20190502_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
